// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6uoIbnSCc7k8y0Mu8OPPzHaTtLp884lA',
    appId: '1:394657733193:web:74aeb7ce61e8cf8ebcbd98',
    messagingSenderId: '394657733193',
    projectId: 'instagram-clone-28888',
    authDomain: 'instagram-clone-28888.firebaseapp.com',
    storageBucket: 'instagram-clone-28888.appspot.com',
    measurementId: 'G-QMCX7EYT3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgPrSJSVQsYEh4t2pYdtfDqoUEXZNHN6I',
    appId: '1:394657733193:android:a59f3f0fe7a976a1bcbd98',
    messagingSenderId: '394657733193',
    projectId: 'instagram-clone-28888',
    storageBucket: 'instagram-clone-28888.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR1a5Ds0cBBLUv4CcqOcr38rHsTSoiTPA',
    appId: '1:394657733193:ios:f664bf3d36e14443bcbd98',
    messagingSenderId: '394657733193',
    projectId: 'instagram-clone-28888',
    storageBucket: 'instagram-clone-28888.appspot.com',
    iosBundleId: 'com.example.instagramCloneFlutter',
  );
}
